Feature/pavlov artem/refine the ability to choose not only a light and dark theme, but also a system one, so that there is automatic switching
V1taS/RandomUIKit pull request #23
Opened 2023-05-07 16:48 UTC by ArtemPavlov72

2023-05-07 19:11 UTC, V1taS requested changes

2023-05-07 19:11 UTC, V1taS commented on RandomUIKitExample/RandomUIKitExample/Modules/CellsScreenModule/Factory/CustomCells/SquircleImageAndLabelWithSegmentedControlCell/CellsScreenDataSource+SquircleImageAndLabelWithSegmentedControlCell.swift
> +
Лишний отступ

2023-05-07 19:11 UTC, V1taS commented on RandomUIKitExample/RandomUIKitExample/Modules/CellsScreenModule/Factory/CustomCells/SquircleImageAndLabelWithSegmentedControlCell/CellsScreenDataSource+SquircleImageAndLabelWithSegmentedControlCell.swift
> +  //let isSwitch: Bool
закоменченный код?

2023-05-07 19:11 UTC, V1taS commented on RandomUIKitExample/RandomUIKitExample/Modules/CellsScreenModule/Factory/CustomCells/SquircleImageAndLabelWithSegmentedControlCell/CellsScreenDataSource+SquircleImageAndLabelWithSegmentedControlCell.swift
> +      SquircleImageAndLabelWithSegmentedControlCellModel(squircleBGColors: [RandomColor.only.primaryGreen,
Можно вот так сноски сделать, будет по приятнее

```
SquircleImageAndLabelWithSegmentedControlCellModel(
        squircleBGColors: [
          RandomColor.only.primaryGreen,
          RandomColor.darkAndLightTheme.primaryGray
        ],
        squircleBGAlpha: 1,
        leftSideImage: UIImage(systemName: "cursorarrow.click.2"),
        leftSideImageColor: .white
      )
```

2023-05-08 20:30 UTC, V1taS approved these changes

2023-05-09 04:45 UTC, ArtemPavlov72 commented on Sources/RandomUIKit/Cells/TableViewCell/SquircleImageAndLabelWithSegmentedControlCell.swift
> +  ///  - isResultSwitch: Значение у переключателя
Описание скорректировано

2023-05-09 04:45 UTC, ArtemPavlov72 commented on Sources/RandomUIKit/Cells/TableViewCell/SquircleImageAndLabelWithSegmentedControlCell.swift
> +                                listOfInterfaceMode: [String],
Для listOfInterfaceMode добавил документацию

2023-05-09 04:46 UTC, ArtemPavlov72 commented on Sources/RandomUIKit/Cells/TableViewCell/SquircleImageAndLabelWithSegmentedControlCell.swift
> +                                interfaceModeValueChanged: ((_ selectedSegmentIndex: Int) -> Void)? = nil) {
Документация добавлена

2023-05-09 04:46 UTC, ArtemPavlov72 commented on Sources/RandomUIKit/Cells/TableViewCell/SquircleImageAndLabelWithSegmentedControlCell.swift
> +    }
Отступ добавил

2023-05-09 04:46 UTC, ArtemPavlov72 commented on Sources/RandomUIKit/Cells/TableViewCell/SquircleImageAndLabelWithSegmentedControlCell.swift
> +    segmentedInterfaceMode.addTarget(self, action: #selector(resultSwitchAction(_:)), for: .valueChanged)
Переносы сделал)

2023-05-09 04:46 UTC, ArtemPavlov72 commented on Sources/RandomUIKit/Cells/TableViewCell/SquircleImageAndLabelWithSegmentedControlCell.swift
> +    guard interfaceModeValueChanged != nil else {
Учел)

2023-05-09 04:47 UTC, ArtemPavlov72 commented on RandomUIKitExample/RandomUIKitExample/Modules/CellsScreenModule/Factory/CustomCells/SquircleImageAndLabelWithSegmentedControlCell/CellsScreenDataSource+SquircleImageAndLabelWithSegmentedControlCell.swift
> +      SquircleImageAndLabelWithSegmentedControlCellModel(squircleBGColors: [RandomColor.only.primaryGreen,
Сноски скорректировал

2023-05-09 04:47 UTC, ArtemPavlov72 commented on RandomUIKitExample/RandomUIKitExample/Modules/CellsScreenModule/Factory/CustomCells/SquircleImageAndLabelWithSegmentedControlCell/CellsScreenDataSource+SquircleImageAndLabelWithSegmentedControlCell.swift
> +
Отступ убрал

2023-05-09 04:49 UTC, merged